# ==============================================================================
# NOVASMART AGENT FRAMEWORK - COMPLETE JUNIOR DEVELOPER GUIDE & REFERENCE CODE
# ==============================================================================
# File: novasmart_agent_framework.py
# Purpose: Educational reference code explaining AI Agent architecture and MCP tools.
# Target Audience: Junior Software Engineers & Platform Engineers.
# ==============================================================================

# ------------------------------------------------------------------------------
# SECTION 1: SYSTEM IMPORTS AND MODULE DEPENDENCIES
# ------------------------------------------------------------------------------

# Import 'json' module: Used for encoding Python dictionaries into JSON formatted strings for API output.
import json

# Import 'sqlite3' module: Provides a lightweight SQL database engine that runs in memory without setup.
import sqlite3

# Import 'typing' annotations: Helps developers understand expected data types for parameters and return values.
from typing import Dict, Any, List, Tuple


# ------------------------------------------------------------------------------
# SECTION 2: DATABASE INITIALIZATION AND SAMPLE DATA CREATION
# ------------------------------------------------------------------------------

def initialize_demo_database() -> sqlite3.Connection:
    """
    Creates an in-memory SQLite database and populates it with sample product data.
    
    Returns:
        sqlite3.Connection: Active database connection object.
    """
    # Step 1: Open an in-memory database connection (":memory:" lives strictly in RAM).
    db_connection = sqlite3.connect(":memory:")
    
    # Step 2: Create a database cursor object (the cursor is used to execute SQL queries).
    db_cursor = db_connection.cursor()
    
    # Step 3: Define the SQL command to create the 'products' table.
    create_table_sql = """
        CREATE TABLE products (
            product_id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            category TEXT NOT NULL,
            price REAL NOT NULL,
            stock_count INTEGER NOT NULL
        )
    """
    # Step 4: Run the table creation SQL statement on the database.
    db_cursor.execute(create_table_sql)
    
    # Step 5: Define a list of tuples containing sample retail product records.
    sample_products = [
        ("P101", "NovaSmart Wireless Earbuds", "Electronics", 49.99, 150),
        ("P102", "NovaSmart Ergonomic Mouse", "Electronics", 29.99, 85),
        ("P103", "NovaSmart USB-C Hub", "Accessories", 19.99, 200)
    ]
    
    # Step 6: Define parameterized SQL query for safe record insertion.
    insert_sql = "INSERT INTO products VALUES (?, ?, ?, ?, ?)"
    
    # Step 7: Execute batch insertion of sample product records into the database table.
    db_cursor.executemany(insert_sql, sample_products)
    
    # Step 8: Commit (save) all database transactions so they are permanently written to memory.
    db_connection.commit()
    
    # Step 9: Return the fully prepared database connection object.
    return db_connection


# ------------------------------------------------------------------------------
# SECTION 3: MODEL CONTEXT PROTOCOL (MCP) TOOL INTEGRATION
# ------------------------------------------------------------------------------

def query_retail_database(query_sql: str, db_connection: sqlite3.Connection) -> List[Dict[str, Any]]:
    """
    Executes a read-only SQL query against the retail database.
    This simulates how an AI agent uses Model Context Protocol (MCP) tools to query data.

    Args:
        query_sql (str): SQL query string generated by or passed to the tool.
        db_connection (sqlite3.Connection): Database connection to execute against.

    Returns:
        List[Dict[str, Any]]: List of dictionary objects, where each key matches a table column.
    """
    # Step 1: Obtain a cursor object from the provided database connection.
    cursor = db_connection.cursor()
    
    # Step 2: Execute the SQL statement passed in the arguments.
    cursor.execute(query_sql)
    
    # Step 3: Extract column header names from the cursor description metadata.
    column_names = [col_description[0] for col_description in cursor.description]
    
    # Step 4: Retrieve all matching rows returned by the query.
    raw_rows = cursor.fetchall()
    
    # Step 5: Convert raw tuple rows into dictionary key-value pairs (column_name: cell_value).
    structured_results = []
    for row in raw_rows:
        # Zip combines the column names list with the row values tuple into pairs.
        row_dict = dict(zip(column_names, row))
        # Append the dictionary row to our result list.
        structured_results.append(row_dict)
        
    # Step 6: Return the clean, structured list of product records.
    return structured_results


# ------------------------------------------------------------------------------
# SECTION 4: AGENT DEFINITION AND TOOL ROUTING CLASS
# ------------------------------------------------------------------------------

class NovaSmartAgent:
    """
    Represents an AI Agent workload capable of understanding prompts,
    executing tools, and returning audited responses.
    """
    
    def __init__(self, agent_name: str, system_instruction: str, db_connection: sqlite3.Connection):
        """
        Initializes the agent instance with an identity, persona, and database tool binding.
        """
        # Property 1: Store the human-readable identifier for the agent.
        self.agent_name = agent_name
        
        # Property 2: Store the system prompt defining the agent's behavior and constraints.
        self.system_instruction = system_instruction
        
        # Property 3: Store the database connection for tool execution.
        self.db_connection = db_connection

    def execute_tool(self, tool_name: str, tool_arguments: Dict[str, Any]) -> Any:
        """
        Dispatches tool execution requests to the appropriate tool function.
        """
        # Check if the tool requested is the database query tool.
        if tool_name == "query_retail_database":
            # Extract the SQL query parameter safely from the dictionary.
            sql = tool_arguments.get("sql", "SELECT * FROM products")
            # Call the database query function and return results.
            return query_retail_database(sql, self.db_connection)
        else:
            # Raise an error if an unauthorized or unknown tool is invoked.
            raise ValueError(f"Unknown tool requested: '{tool_name}'")

    def process_user_prompt(self, prompt_text: str) -> Dict[str, Any]:
        """
        Processes an incoming user request, determines tool requirements, and generates output.
        """
        # Step 1: Print a log line indicating the prompt received.
        print(f"[{self.agent_name}] Processing user prompt: '{prompt_text}'")
        
        # Step 2: Determine if database lookup tool execution is required based on prompt content.
        requires_product_lookup = "product" in prompt_text.lower() or "price" in prompt_text.lower()
        
        if requires_product_lookup:
            # Construct read-only SQL query string for product retrieval.
            target_sql = "SELECT product_id, name, price, stock_count FROM products"
            
            # Execute the tool via the internal router.
            data_output = self.execute_tool("query_retail_database", {"sql": target_sql})
            
            # Construct structured audit response dictionary.
            return {
                "agent_name": self.agent_name,
                "status": "SUCCESS",
                "message": f"Retrieved {len(data_output)} products from database.",
                "data": data_output
            }
        else:
            # Construct response dictionary when no tool calls are needed.
            return {
                "agent_name": self.agent_name,
                "status": "SUCCESS",
                "message": "Prompt processed successfully without tool invocation.",
                "data": []
            }


# ------------------------------------------------------------------------------
# SECTION 5: SCRIPT EXECUTION ENTRYPOINT
# ------------------------------------------------------------------------------

if __name__ == "__main__":
    # Step 1: Initialize the demo SQLite database.
    database = initialize_demo_database()
    
    # Step 2: Create an instance of NovaSmartAgent representing a retail catalog assistant.
    retail_agent = NovaSmartAgent(
        agent_name="Retail Catalog Agent",
        system_instruction="You assist retail operations by retrieving product details safely.",
        db_connection=database
    )
    
    # Step 3: Run a sample user prompt inquiring about product pricing.
    agent_response = retail_agent.process_user_prompt("Can you list all available products and prices?")
    
    # Step 4: Pretty-print the structured JSON output to the console for review.
    print(json.dumps(agent_response, indent=2))
